# permissions for end users to edit mcpservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sample-component
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-editor-role
rules:
- apiGroups:
  - mcpserver.opendatahub.io
  resources:
  - mcpservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcpserver.opendatahub.io
  resources:
  - mcpservers/status
  verbs:
  - get
