---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
- apiGroups:
  - helloworld.opendatahub.io
  resources:
  - helloworlds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helloworld.opendatahub.io
  resources:
  - helloworlds/finalizers
  verbs:
  - update
- apiGroups:
  - helloworld.opendatahub.io
  resources:
  - helloworlds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
