apiVersion: helloworld.opendatahub.io/v1
kind: HelloWorld
metadata:
  labels:
    app.kubernetes.io/name: sample-component
    app.kubernetes.io/managed-by: kustomize
  name: helloworld-sample
spec:
  # TODO(user): Add fields here
