apiVersion: mcpserver.opendatahub.io/v1
kind: MCPServer
metadata:
  labels:
    app.kubernetes.io/name: sample-component
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-sample
spec:
  # TODO(user): Add fields here
